# Checker utilities for the testcase-generator framework

"""Helper functions to detect and bundle a custom checker.

A problem may optionally contain a ``checker.py`` file next to the
``spec.py`` and ``solution.cpp``.  When present, the generator will copy it
into the final HackerRank ZIP under ``checker/checker.py``.

The public API mirrors the plan:

* ``load_checker(problem_dir)`` - return ``Path`` to the checker or ``None``
* ``bundle_checker(zip_path, checker_path)`` - add the checker to the ZIP
"""

import pathlib
import zipfile

def load_checker(problem_dir: pathlib.Path) -> pathlib.Path | None:
    """Return the path to ``checker.py`` inside *problem_dir* if it exists.

    The function validates that the module defines a ``run_custom_checker``
    callable with the correct signature.  If the file is missing or the
    validation fails, ``None`` is returned.
    """
    checker_path = problem_dir / "checker.py"
    if not checker_path.is_file():
        return None
    # Basic validation - import the module in an isolated namespace
    import importlib.util
    spec = importlib.util.spec_from_file_location("checker_module", str(checker_path))
    mod = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(mod)
    except Exception as e:
        raise RuntimeError(f"Failed to import checker at {checker_path}: {e}")
    if not hasattr(mod, "run_custom_checker"):
        raise RuntimeError(f"Checker {checker_path} does not define run_custom_checker")
    return checker_path


def bundle_checker(zip_path: pathlib.Path, checker_path: pathlib.Path) -> None:
    """Add ``checker.py`` to *zip_path* under the ``checker/`` folder.

    The function opens the ZIP in *append* mode and writes the file with the
    internal name ``checker/checker.py``.  Existing ``checker/`` entries are
    overwritten.
    """
    with zipfile.ZipFile(zip_path, "a", zipfile.ZIP_DEFLATED) as zf:
        internal_name = "checker/checker.py"
        zf.writestr(internal_name, checker_path.read_text(encoding="utf-8"))


def ensure_checker(problem_dir: pathlib.Path) -> pathlib.Path:
    """Create a default ``checker.py`` in *problem_dir* if it does not exist.

    Writes the user-provided template to guarantee a checker for each problem.
    Returns the path to the checker file (new or existing).
    """
    checker_path = problem_dir / "checker.py"
    if not checker_path.is_file():
        default_template = """# Start of BODY
'''\\
TestStruct::
testcase_id                   [int] ID of the test-case
testcase_input_path           [str] File path to test-case input
testcase_output_path          [str] File path to test-case output generated by the problem solver
testcase_expected_output_path [str] File path to test-case expected output to be matched with
testcase_error_path           [str] File path to test-case STDERR
metadata_file_paths           [list<str>] File paths to Question metadata (Extra files usually used for defining traning sets)
submission_code_path          [str] File path to submission source code
submission_language           [str] Language token of submission
testcase_result               [bool] Set to True if test-case output matches test-case expected output. Matching is done line by line
testcase_signal               [int] Exit code of the test-case process
testcase_time                 [float] Time taken by the test-case process in seconds
testcase_memory               [int] Peak memory of the test-case process determined in bytes
data                          [str] <Future use>
ResultStruct::
result      [bool]  Assign test-case result. True determines success. False determines failure
score       [float] Assign test-case score. Normalized between 0 to 1
message     [str] Assign test-case message. This message is visible to the problem solver
'''\\

def run_custom_checker(t_obj, r_obj):
    # Don't print anything to STDOUT in this function
    # Custom scoring logic
    r_obj.result = True
    r_obj.score = 1.0
    r_obj.message = "Success"
# End of BODY"""
        checker_path.write_text(default_template.strip() + "\n")
    return checker_path
